### ISSUE TITLE
想挂GitHub报错

### ISSUE THREAD

**Issue by qhq** [ziye12/JavaScript#4]
/home/runner/work/Self/Self/execute.js:207
else if (i==3&&task.data.treasureBox.doneFlag==0)
               ^

ReferenceError: task is not defined
    at Timeout._onTimeout (/home/runner/work/Self/Self/execute.js:207:16)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

**Comment by qhq** [comment]
/home/runner/work/Self/Self/execute.js:208
else if (i==3&&task.data.treasureBox.doneFlag==0)
                         ^

TypeError: Cannot read property 'treasureBox' of ***
    at Timeout._onTimeout (/home/runner/work/Self/Self/execute.js:208:26)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

**Comment by tommyhe1217** [comment]
> /home/runner/work/Self/Self/execute.js:208
> else if (i==3&&task.data.treasureBox.doneFlag==0)
> ^
> 
> TypeError: Cannot read property 'treasureBox' of ***
> at Timeout._onTimeout (/home/runner/work/Self/Self/execute.js:208:26)
> at ontimeout (timers.js:436:11)
> at tryOnTimeout (timers.js:300:5)
> at listOnTimeout (timers.js:263:5)
> at Timer.processTimers (timers.js:223:10)

请问一下，qq阅读, Actions跑，secrets填的什么数据？

**Comment by qhq** [comment]
看个人设置的，我的是话是把4个参数用换行分隔后填到一个secret里

**Comment by tommyhe1217** [comment]
> 看个人设置的，我的是话是把4个参数用换行分隔后填到一个secret里

参数哪里提取的啊，有对应box吗？

**Comment by qhq** [comment]
没有，参数就是作者js里涉及的那4个。自己抓可以，跑脚本看log也可以

**Comment by tommyhe1217** [comment]
> 没有，参数就是作者js里涉及的那4个。自己抓可以，跑脚本看log

ok，谢了
